### ISSUE TITLE
Moocha is present in Merriam-Webster

### ISSUE THREAD

**Issue by nMoncho** [standardebooks/h-rider-haggard_king-solomons-mines#1]
Hi,
Looking at the diff, _Moocha_ went from being wrapped with a **span** to an **i** tag, but the word is present in the dictionary.
According to the typography manual, words that are in it mustn't be set in italics.
https://www.merriam-webster.com/dictionary/moocha

**Comment by acabal** [comment]
I made an editorial decision since that word is extremely obscure, is being used in a native context, and includes a definition in the text itself.
